name: Deploy 'site/' to Neocities

on:
  push:
    branches:
      - main  # or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install zip and curl
        run: sudo apt-get update && sudo apt-get install -y zip curl

      - name: Zip site directory
        run: |
          cd site
          zip -r ../site.zip .  # Zip everything in 'site/' into a file at the root

      - name: Upload to Neocities
        run: |
          curl -F "file=@site.zip" \
               -H "Authorization: Bearer ${{ secrets.NEOCITIES_API_KEY }}" \
               https://neocities.org/api/upload
